FORMAT: 1A
HOST: https://api.getheadlines.io/

# Get Headlines API

The **Get Headlines REST API** offers access and control over Get Headlines data, such as Sources (Feed providers) and Feeds.

In order to access the Get Headlines API, there are some things you first need to know. 

Read the sections below before you start using the Get Headlines API.

Most API resources are protected with **JSON Web Token Authentication**. 
You first need to register. Upon registration, you need to login to receive your personal API KEY, that allows you to authenticate against the API.

Once you have your private Authentication key, you can use it to authenticate your HTTP requests to the API. You can do so by adding an Authorization header to all your HTTP calls. 

The Authorization Header is formatted as such: 

`Authorization: Bearer JSWON_WEB_TOKEN`


## Authentication [/auth]

### Login [POST]

*Note*: You have to be registered user to use login.

+ Request (application/json)

        {
            "email": "user@gmail.com",
            "password": "StrongPassword"
        }

+ Response 200 (application/json)

    Returned if provided email and password are valid.

    + Body

            {
                "status": "ok",
                "message": {
                    "token" "YOUR PERSONAL JSON WEB TOKEN"
                }
                
            }
            
+ Response 401 (application/json)

    Returned if provided password did not match.
    
    + Body

            {
                "status": "error",
                "message": "InvalidPassword"
                
            }
            
+ Response 404 (application/json)

    Returned if provided email is not recognized (not used for registration).
    
    + Body

            {
                "status": "error",
                "message": "UserNotFound"
                
            }


## User [/user]

### Register [POST]

+ Request (application/json)

        {
            "name": "User Name",
            "email": "user@gmail.com",
            "password": "StrongPassword"
        }

+ Response 201 (application/json)

    Returned if a user was successfully created.

    + Body

            {
                "status": "ok",
                "user": {
                    "email" "user@gmail.com"
                }
                
            }

+ Response 400 (application/json)

    Returned if email or password are not provided.
    
    + Body

            {
                "status": "error",
                "message": "ParameterMissing"
                
            }

+ Response 409 (application/json)

    Returned if a user with given email already exist.
    
    + Body

            {
                "status": "error",
                "message": "AlreadyExist"
                
            }
            
+ Response 422 (application/json)

    Returned if provided parameters are not valid. (ex. Invalid email)
    
    + Body

            {
                "status": "error",
                "message": "ParameterInvalid"
                
            }

### Get User (self) [GET]

+ Request

    + Headers

            Authorization: Bearer JWT

+ Response 200 (application/json)

        {
            "status": "ok",
            "user": {
                "name": "User Name",
                "email" "user@gmail.com",
                "registered": "2018-04-21T21:54:56.365Z",
                "verified": false
            }
            
        }

### Delete User (self) [DELETE]

+ Request

    + Headers

            Authorization: Bearer JWT

+ Response 200 (application/json)

    + Body

            {
                "status": "ok",
                "message": "User with id 1 deleted."
                
            }
  
            
## Sources [/sources]

### Get Sources [GET]

+ Request

    + Headers

            Authorization: Bearer JWT

+ Response 200 (application/json)

        {
            "status": "ok",
            "sources": [
                {
                    "id": "cnbc",
                    "name": "CNBC",
                    "description": "CNBC World News",
                    "homepage": "https://www.cnbc.com",
                    "language": "en",
                    "country": "world",
                    "category": "general"
                }
            ]
            
        }

     
## Feeds [/feeds{?sources,includeContent,language,pageSize,page}]

### Get Feeds [GET]

+ Parameters

    + sources: `cnbc` (enum[SourceId], optional) - Array of Source Id's. Use this to get feeds from custom Sources (maximum 5)
    + includeContent: `false` (boolean, optional) - Include article content in response. Default `false`.
    + language: `all` (string, optional) - The 2-letter ISO-639-1 code of the language you want to get feeds for. Default: `all` languages.
    + pageSize: `1` (number, optional) - The number of results to return per page. 20 is the default, 100 is the maximum.
    + page: `0` (number, optional) - Use this to page through the results. Page count starts from 0.

+ Request

    + Headers

            Authorization: Bearer JWT
            

+ Response 200 (application/json)

        {
            "status": "ok",
            "totalResults": "34",
            "query": {
                "sources": [
                    "cnbc"
                ],
                "includeContent": false,
                "language": "all",
                "pageSize": 1,
                "page": 0
            },
            "feeds": [
                {
                    "title": "Iran warns against Trump deals as US, North Korea plan to meet",
                    "publishedAt": "2018-04-22T10:30:00.000Z",
                    "url": "https://www.cnbc.com/2018/04/22/as-u-s-north-korea-plan-to-meet-iran-warns-against-trump-deals.html",
                    "description": "A U.S. push to change the Iran nuclear deal was sending a “very dangerous message” that countries should never negotiate with Washington, Iran’s foreign minister warned.",
                    "author": "CNBC",
                    "source": {
                        "id": "cnbc",
                        "name": "CNBC"
                    }
                }
            ]
            
        }
        
+ Response 422 (application/json)

    Returned if provided query parameters are not valid.
    
    + Body

            {
                "status": "error",
                "message": "ParameterInvalid"
                
            }