FORMAT: 1A
HOST: https://api.getheadlines.io/

# Get Headlines

Automates XML/RSS feed parsing into JSON and exposes data via REST API

## User [/user]

### Get User (self) [GET]

+ Request

    + Headers

            Authorization: Bearer TOKEN

+ Response 200 (application/json)

        {
            "status": "ok",
            "user": {
                "name": "User Name",
                "email" "user@gmail.com",
                "registered": 1524179174
            }
            
        }

### Add New User [POST]

+ Request (application/json)

        {
            "name": "User Name",
            "email": "user@gmail.com",
            "password": "StrongPassword"
        }

+ Response 201 (application/json)

    Returned if a user was successfully created.

    + Body

            {
                "status": "ok",
                "user": {
                    "email" "user@gmail.com"
                }
                
            }
            
+ Response 409 (application/json)

    Returned if a user with given email already exist.
    
    + Body

            {
                "status": "error",
                "message": "AlreadyExist"
                
            }

+ Response 400 (application/json)

    Returned if email or password are not provided.
    
    + Body

            {
                "status": "error",
                "message": "ParameterMissing"
                
            }
            
+ Response 422 (application/json)

    Returned if provided parameters are not valid. (ex. Invalid email, or password less than 8 characters)
    
    + Body

            {
                "status": "error",
                "message": "ParameterInvalid"
                
            }
            
### Delete User (self) [DELETE]

+ Request

    + Headers

            Authorization: Bearer TOKEN

+ Response 200 (application/json)

    + Body

            {
                "status": "ok",
                "message": "User with id 1 deleted."
                
            }